//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiveItBack.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GiveItBack.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna nazwa nowego uczestnika.
        /// </summary>
        public static string strAddMemWarTopic {
            get {
                return ResourceManager.GetString("strAddMemWarTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź wysokość wkładu.
        /// </summary>
        public static string strConfirmValue {
            get {
                return ResourceManager.GetString("strConfirmValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trwa wyszukiwanie kontaktów....
        /// </summary>
        public static string strContactsSearching {
            get {
                return ResourceManager.GetString("strContactsSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba znalezionych kontaktów.
        /// </summary>
        public static string strFoundContactsCount {
            get {
                return ResourceManager.GetString("strFoundContactsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string strHistory {
            get {
                return ResourceManager.GetString("strHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadzoną wartość ciężko zmienić na złotówki....
        /// </summary>
        public static string strInvalidValue {
            get {
                return ResourceManager.GetString("strInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna wartość.
        /// </summary>
        public static string strInvalidValueTopic {
            get {
                return ResourceManager.GetString("strInvalidValueTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono żadnych kontaktów..
        /// </summary>
        public static string strNoContactsFound {
            get {
                return ResourceManager.GetString("strNoContactsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano żadnego kontaktu..
        /// </summary>
        public static string strNonSelectedContact {
            get {
                return ResourceManager.GetString("strNonSelectedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wprowadzono żadnej nazwy nowego uczestnika..
        /// </summary>
        public static string strNonSelectedMember {
            get {
                return ResourceManager.GetString("strNonSelectedMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz uczestnika.
        /// </summary>
        public static string strWorkBarSelectMember {
            get {
                return ResourceManager.GetString("strWorkBarSelectMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj uczestnika.
        /// </summary>
        public static string WorkBarAddMember {
            get {
                return ResourceManager.GetString("WorkBarAddMember", resourceCulture);
            }
        }
    }
}
